// src/App.jsx — Generated by VIA for: Build an AI-powered “Emergency Migration Assistant” platform for migrant workers in India. The system should allow users to register using Aadhaar-based OTP verification, upload documents, and request emergency government services remotely without visiting offices physically.
import { useState, useRef, useCallback } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import axios from "axios";

const BASE_URL = import.meta.env.VITE_API_URL ||
  (typeof window !== "undefined" && (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1")
    ? "http://localhost:8000" : "");

export default function App() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const inputRef = useRef(null);

  const handleFile = useCallback((f) => {
    if (!f || !f.type.startsWith("image/")) { toast.error("Please select an image file"); return; }
    setFile(f);
    setResult(null);
    const reader = new FileReader();
    reader.onload = (e) => setPreview(e.target.result);
    reader.readAsDataURL(f);
  }, []);

  const handleDrop = (e) => {
    e.preventDefault(); setDragOver(false);
    handleFile(e.dataTransfer.files[0]);
  };

  const handleProcess = async () => {
    if (!file) { toast.error("Please select an image first"); return; }
    setLoading(true);
    try {
      const fd = new FormData();
      fd.append("file", file);
      const res = await axios.post(`${BASE_URL}/api/v1/process`, fd, {
        headers: { "Content-Type": "multipart/form-data" },
        responseType: "blob",
      });
      setResult(URL.createObjectURL(res.data));
      toast.success("Image processed successfully!");
    } catch (err) {
      toast.error(err.response?.data?.detail || "Processing failed — backend may be starting up");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;
    const a = document.createElement("a");
    a.href = result; a.download = "processed_" + (file?.name || "image.png");
    a.click();
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#eef2ff" }}>
      <ToastContainer position="top-right" autoClose={3000} />
      <nav className="bg-white border-b border-gray-100 shadow-sm sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center gap-3">
          <span className="text-2xl">🖼️</span>
          <span className="font-bold text-gray-900 text-lg">Build An Ai Powered Emergency Migration Assistant Platform</span>
        </div>
      </nav>
      <main className="max-w-5xl mx-auto px-6 py-10 space-y-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900">Build An Ai Powered Emergency Migration Assistant Platform</h1>
          <p className="text-gray-500 mt-2">Upload an image and process it instantly</p>
        </div>

        {/* Upload Zone */}
        <div
          onDrop={handleDrop} onDragOver={e => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)} onClick={() => inputRef.current?.click()}
          className={`card border-2 border-dashed cursor-pointer text-center py-16 transition-all ${
            dragOver ? "border-indigo-400 bg-indigo-50" : "border-gray-200 hover:border-indigo-300"
          }`}
        >
          <input ref={inputRef} type="file" accept="image/*" className="hidden" onChange={e => handleFile(e.target.files[0])} />
          <div className="text-5xl mb-4">🖼️</div>
          <p className="text-gray-600 font-medium">Drop an image here or <span style={{ color: "#6366f1" }}>browse</span></p>
          <p className="text-gray-400 text-sm mt-1">PNG, JPG, WEBP, GIF supported</p>
        </div>

        {/* Preview + Result */}
        {(preview || result) && (
          <div className={`grid gap-6 ${result ? "grid-cols-1 md:grid-cols-2" : "grid-cols-1 max-w-md mx-auto"}`}>
            {preview && (
              <div className="card space-y-3">
                <h2 className="font-semibold text-gray-700">Original</h2>
                <img src={preview} alt="original" className="w-full rounded-xl object-contain max-h-80" />
                <p className="text-xs text-gray-400">{file?.name} · {(file?.size / 1024).toFixed(1)} KB</p>
              </div>
            )}
            {result && (
              <div className="card space-y-3">
                <h2 className="font-semibold text-gray-700">Processed</h2>
                <img src={result} alt="processed" className="w-full rounded-xl object-contain max-h-80" />
                <button onClick={handleDownload} className="btn-secondary w-full text-sm">⬇ Download</button>
              </div>
            )}
          </div>
        )}

        {preview && (
          <div className="flex justify-center">
            <button onClick={handleProcess} disabled={loading} className="btn-primary px-10 py-3 text-base">
              {loading ? "Processing…" : "Process Image"}
            </button>
          </div>
        )}
      </main>
    </div>
  );
}
